# Identificación del proyecto y organización
sonar.projectKey=valentina-ochoa_AutoParts
sonar.organization=valentina-ochoa

# URL de SonarCloud
sonar.host.url=https://sonarcloud.io

# Token de autenticación
sonar.login=TU_TOKEN

# Carpeta donde están tus archivos fuente
sonar.sources=.

# Codificación de los archivos
sonar.sourceEncoding=UTF-8
