# Generated by Django 5.2.1 on 2025-06-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuario_direccion_usuario_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='etiquetas',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Etiquetas del Producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_producto',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código del Producto'),
        ),
    ]
