# Generated by Django 5.2.1 on 2025-06-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_producto_codigo_interno'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(blank=True, max_length=150, null=True)),
                ('accion', models.CharField(max_length=32)),
                ('modelo', models.CharField(blank=True, max_length=64, null=True)),
                ('detalles', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
