# Generated by Django 5.2.1 on 2025-06-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_clientedistribuidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_mayorista',
            field=models.IntegerField(default=999999999, verbose_name='Precio Mayorista (CLP)'),
        ),
    ]
