# Generated by Django 5.2.1 on 2025-07-02 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_producto_precio_mayorista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='estado',
        ),
    ]
