# Generated by Django 5.2.1 on 2025-07-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_carrito_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_creacion',
        ),
    ]
