# Generated by Django 5.2.1 on 2025-07-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_usuario_fecha_creacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogAuditoria',
        ),
    ]
