# Generated by Django 5.2.1 on 2025-07-02 18:17

import django.contrib.admin.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('api', '0009_delete_logauditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntryProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin.logentry',),
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
